---
title: Statistical Analysis Plan for Modelling biological systems with nonparametric models
author: "Hongjin Ren"
date: '2022-06-17'
output: pdf_document
---

## **Primary Objective**
+ Comparing the performance of smoothed splines with more commonly used parametric models (e.g. linear regression models).
+ Comparing the performance of smoothed splines with other nonparametric models such as RKHS.

## **Secondary Objectives**
+ Generate simulated data using different ODE models to compare the performance of different algorithms.

## **Data Collection methods**
+ Data can be generated by running the code in the R package KGode.
+ Fitting different ordinary differential equations to obtain data for different models.


## **Variables under consideration**
+ **Primary objective outcome**: Calculate the root mean square error of the prediction and the true value.
+ **secondary objective outcome**: Calculate and compare the time used to obtain the results for the different methods.

## **Numerical and graphical summaries to be presented**


## **Models to be fitted**


